# Assignment-1

<div align="center">
<img src="img/asgn.jpg" alt="asgn.jpg" width="1000px">
</div>

In [76]:
"""
cd .\04assignment\
jupyter nbconvert --to markdown asng.ipynb --output README.md
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk

## Load Data

### Processing file - test codes

In [27]:
with open('38943-0.txt', 'r') as target_file:
	for num, line in enumerate(target_file.readlines()):
		if "Title" in line:
			title = line.split(":")[1].strip()
			print(title)
		if "Author" in line:
			author_name = line.split(":")[1].strip()
			print(author_name)
author_list = [author_name]*5
author_list

Science and Medieval Thought
Sir Thomas Clifford Allbutt


['Sir Thomas Clifford Allbutt',
 'Sir Thomas Clifford Allbutt',
 'Sir Thomas Clifford Allbutt',
 'Sir Thomas Clifford Allbutt',
 'Sir Thomas Clifford Allbutt']

In [3]:
out = open("64171-0_chapter.txt", "w")
with open('64171-0.txt', 'r') as f:
	data = f.read()
	if "CHAPTER I." in data:
		data = data.replace("CHAPTER I.", "CHAPTERI.")
		print(data, file=out)
out.close()


In [4]:
list_of_blocks = []
with open('64171-0_chapter.txt', 'r') as f:
	data = f.read()
	# print(len(data.split()))
	total_word = len(data.split())
	data = data.split()
	# indices = []
	# for i, w in enumerate(data):
	# 	# start reading from CHAPTER I.
	# 	if "CHAPTERI" in w:
	# 		indices.append(i)
	# last = indices[-1]
	# # print(last)
	# data = data[last+1:]

	n = 200
	for i in range(n):
		s = round(total_word*i/n)
		e = round(total_word*(1+i)/n)
		# print(s,e)
		chunks = data[s:e]
		chunks = " ".join(chunks)
		# print(chunks)
		# print(100*"=")
		list_of_blocks.append(chunks)

# print(list_of_blocks)


### Processing file - Final

In [77]:
import os
def getTextFileList():
	all_files = os.listdir()
	txt_files = []
	for file in all_files:
		if file.endswith(".txt"):
			txt_files.append(file)
	return txt_files

In [78]:
from termcolor import cprint
def processFiles(text_files,document_no=200):
	df_obj_of_documents = {
		"documents":[],
		"author":[]
	}
	list_of_documents = []
	list_of_authors = []
	for file in text_files:
		cprint(f"Extracting from: {file}", 'green')
		# get Title and Author name
		author_name=""
		with open(file, 'r') as target_file:
			for num, line in enumerate(target_file.readlines()):
				pass
				if "Title:" in line:
					title = line.split(":")[1].strip()
				if "Author:" in line:
					print(line)
					author_name = line.split(":")[1].strip()

		# get documents from each file
		with open(file, 'r') as f:
			data = f.read()
			total_word = len(data.split())
			data = data.split()
			# indices = []
			# for i, w in enumerate(data):
			# 	# start reading from CHAPTER I.
			# 	if "CHAPTERI" in w:
			# 		indices.append(i)
			# last = indices[-1]
			# # print(last)
			# data = data[last+1:]

			# n = 200
			for i in range(document_no):
				start_from = round(total_word*i/document_no)
				end_at = round(total_word*(1+i)/document_no)
				document = data[start_from:end_at]
				document = " ".join(document)
				# print(chunks)
				# print(100*"=")
				list_of_documents.append(document)
				
		print("Book Title: ",end="")
		cprint(title, 'yellow')		
		print("Author: ",end="")
		cprint(author_name, 'yellow')
		# generated_doc_size = len(list_of_documents)
		print("Documents generated: ",end="")
		cprint(document_no, 'yellow')
		repeating_author = [author_name]*document_no
		# print(repeating_author)
		list_of_authors = list_of_authors + repeating_author
		# save to dataframe
	df_obj_of_documents["author"] = list_of_authors
	df_obj_of_documents["documents"] = list_of_documents
	# print(df_obj_of_documents)
	print(len(list_of_authors))
	print(len(list_of_documents))
	return df_obj_of_documents


In [79]:
df_obj_of_documents = processFiles(getTextFileList(),document_no=200)

Extracting from: 38943-0.txt
Author: Sir Thomas Clifford Allbutt

Book Title: Science and Medieval Thought
Author: Sir Thomas Clifford Allbutt
Documents generated: 200
Extracting from: 64171-0.txt
Author: Robert C. (Chamblet) Adams

Book Title: On Board the "Rocket"
Author: Robert C. (Chamblet) Adams
Documents generated: 200
Extracting from: 65708-0.txt
Author: Averroes

Book Title: The Philosophy and Theology of Averroes
Author: Averroes
Documents generated: 200
Extracting from: pg24055.txt
Author: Confucius

Book Title: The Sayings Of Confucius
Author: Confucius
Documents generated: 200
Extracting from: pg2412.txt
Author: Aristotle

Book Title: The Categories
Author: Aristotle
Documents generated: 200
Extracting from: pg34283.txt
Author: Alfred William Benn

Book Title: History of Modern Philosophy
Author: Alfred William Benn
Documents generated: 200
Extracting from: pg66566.txt
Author: T.J. de Boer

Book Title: The History of Philosophy in Islam
Author: T.J. de Boer
Documents genera

In [80]:
import pandas as pd
# df = pd.DataFrame({
# 	'data': list_of_blocks,
# 	"author": author_list
# })
df = pd.DataFrame(df_obj_of_documents)
df.head()

documents  \
0  The Project Gutenberg eBook, Science and Medi...   
1  SCIENCE AND MEDIEVAL THOUGHT. * * * * * London...   
2  et facit nos concludere quæstionem, sed non ce...   
3  a phantom, and again the spirit of a new world...   
4  first applied to the art and romance of the Mi...   

                        author  
0  Sir Thomas Clifford Allbutt  
1  Sir Thomas Clifford Allbutt  
2  Sir Thomas Clifford Allbutt  
3  Sir Thomas Clifford Allbutt  
4  Sir Thomas Clifford Allbutt

In [81]:
df['words_count'] = df['documents'].apply(lambda x: len(x.split()))
df.head()

documents  \
0  The Project Gutenberg eBook, Science and Medi...   
1  SCIENCE AND MEDIEVAL THOUGHT. * * * * * London...   
2  et facit nos concludere quæstionem, sed non ce...   
3  a phantom, and again the spirit of a new world...   
4  first applied to the art and romance of the Mi...   

                        author  words_count  
0  Sir Thomas Clifford Allbutt          142  
1  Sir Thomas Clifford Allbutt          143  
2  Sir Thomas Clifford Allbutt          142  
3  Sir Thomas Clifford Allbutt          142  
4  Sir Thomas Clifford Allbutt          143

In [47]:
df['words_count'].min()

87

In [82]:
df = df.drop(df[df['words_count'] < 100].index)
# drop documents with less than 100 words

In [49]:
df['words_count'].min()

142

### Label Encoding

#### using `pd.factorize()`

In [50]:
y , label = df['author'].factorize()
label

Index(['Sir Thomas Clifford Allbutt', 'Robert C. (Chamblet) Adams', 'Averroes',
       'Confucius', 'Alfred William Benn', 'T.J. de Boer'],
      dtype='object')

In [41]:
np.unique(y)

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [42]:
if_predit = 1
label[if_predit]

'Robert C. (Chamblet) Adams'

In [52]:
df['label'] = y
df.head()

documents  \
0  The Project Gutenberg eBook, Science and Medi...   
1  SCIENCE AND MEDIEVAL THOUGHT. * * * * * London...   
2  et facit nos concludere quæstionem, sed non ce...   
3  a phantom, and again the spirit of a new world...   
4  first applied to the art and romance of the Mi...   

                        author  words_count  label  
0  Sir Thomas Clifford Allbutt          142      0  
1  Sir Thomas Clifford Allbutt          143      0  
2  Sir Thomas Clifford Allbutt          142      0  
3  Sir Thomas Clifford Allbutt          142      0  
4  Sir Thomas Clifford Allbutt          143      0

In [54]:
# shuffle data
df = df.sample(frac=1).reset_index(drop=True)
df.head()

documents  \
0  is beneath it, and through logical inference w...   
1  “If we had pleased, we had certainly given eve...   
2  astronomy, and alchemy. Averroes it was who fi...   
3  matter of principle there can of course be but...   
4  also the masts and yards, and wearing away the...   

                        author  words_count  label  
0                 T.J. de Boer          320      5  
1                     Averroes          277      2  
2  Sir Thomas Clifford Allbutt          142      0  
3   Robert C. (Chamblet) Adams          394      1  
4   Robert C. (Chamblet) Adams          395      1

#### using `sklearn.preprocessing.LabelEncoder()`

In [83]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()


In [84]:
df['label'] = labelencoder.fit_transform( df['author'])
df.head()

documents  \
0  The Project Gutenberg eBook, Science and Medi...   
1  SCIENCE AND MEDIEVAL THOUGHT. * * * * * London...   
2  et facit nos concludere quæstionem, sed non ce...   
3  a phantom, and again the spirit of a new world...   
4  first applied to the art and romance of the Mi...   

                        author  words_count  label  
0  Sir Thomas Clifford Allbutt          142      4  
1  Sir Thomas Clifford Allbutt          143      4  
2  Sir Thomas Clifford Allbutt          142      4  
3  Sir Thomas Clifford Allbutt          142      4  
4  Sir Thomas Clifford Allbutt          143      4

In [85]:
# shuffle data
df = df.sample(frac=1).reset_index(drop=True)
df.head()


documents  \
0  its place. According to Cousin, in all countri...   
1  families of Meng, Shu, and Chi were descended,...   
2  were the conjectures about her, and some of ou...   
3  He is the author of the famous saying--the sol...   
4  not truthful, I will know nothing. 17. The Mas...   

                       author  words_count  label  
0         Alfred William Benn          220      0  
1                   Confucius          173      2  
2  Robert C. (Chamblet) Adams          395      3  
3         Alfred William Benn          220      0  
4                   Confucius          173      2

## Data Pre-Process

In [86]:
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import re
ps = PorterStemmer()


In [56]:
def text_process(msg):
	# Remove Emails
	msg = re.sub('\b[\w\-.]+?@\w+?\.\w{2,4}\b', 'emailaddr', msg)
	# Remove url's
	msg = re.sub('(http[s]?\S+)|(\w+\.[A-Za-z]{2,4}\S*)', 'httpaddr', msg)
	# Remove Money Symbols
	msg = re.sub('£|\$', 'moneysymb', msg)
	# Remove Phone Numbers
	msg = re.sub(
		'\b(\+\d{1,2}\s?\d?[\-(.]?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})\b', 'phonenumbr', msg)
	# Remove Numbers
	msg = re.sub('\d+(\.\d+)?', '', msg)
	# Remove Punctuation
	msg = re.sub('[^\w\s]', '', msg)
	# Remove Extra Spaces
	msg = re.sub('\s+', ' ', msg)

	# Lower case
	msg = msg.lower()

	# Tokenize
	words = word_tokenize(msg)

	# Remove Stop Words
	stop_words = set(stopwords.words('english'))
	words = [w for w in words if not w in stop_words]

	# Stemming
	stemmed_words = [ps.stem(w) for w in words]

	# Join the words back into one string separated by space,
	stemmed_sen = ' '.join(stemmed_words)

	return stemmed_sen


In [57]:
df['clean_msg'] = df.documents.apply(text_process)
df.head()

documents  \
0  is beneath it, and through logical inference w...   
1  “If we had pleased, we had certainly given eve...   
2  astronomy, and alchemy. Averroes it was who fi...   
3  matter of principle there can of course be but...   
4  also the masts and yards, and wearing away the...   

                        author  words_count  label  \
0                 T.J. de Boer          320      5   
1                     Averroes          277      2   
2  Sir Thomas Clifford Allbutt          142      0   
3   Robert C. (Chamblet) Adams          394      1   
4   Robert C. (Chamblet) Adams          395      1   

                                           clean_msg  
0  beneath logic infer final ration consider dire...  
1  pleas certainli given everi soul direct word h...  
2  astronomi alchemi averro first assert independ...  
3  matter principl cours one answerchrist teach e...  
4  also mast yard wear away deck holyston well le...

In [58]:
df['documents'].iloc[0]


'is beneath it, and through logical inference with what is above it, and finally with itself by rational consideration or direct intuition. Of these kinds of knowledge the surest and the most deserving of preference is knowledge of one’s self. When human knowledge attempts to go farther than this, it proves itself to be limited in many ways. Therefore one must not philosophize straight away about questions like the origin or the eternity of the world, but make his first essays with what is simpler. And only through renunciation of the world, and righteous conduct, does the soul lift itself gradually up to the pure knowledge of the Highest.” 5. After secular instruction in Grammar, Poetry and History, and after religious education and doctrine, philosophic study should begin with the mathematical branches. Here everything is set forth in Neo-Pythagorean and Indian fashion. Not only numbers but even the letters of the alphabet are employed in childish trifling. It was particularly conven

In [59]:
df['clean_msg'].iloc[0]


'beneath logic infer final ration consider direct intuit kind knowledg surest deserv prefer knowledg one self human knowledg attempt go farther prove limit mani way therefor one must philosoph straight away question like origin etern world make first essay simpler renunci world righteou conduct soul lift gradual pure knowledg highest secular instruct grammar poetri histori religi educ doctrin philosoph studi begin mathemat branch everyth set forth neopythagorean indian fashion number even letter alphabet employ childish trifl particularli conveni brethren number letter arab alphabet multipli instead proceed accord practic real point view give rein fanci scienc accord grammat analog relat number arithmet investig number rather signific search made suitabl mode express number case phenomena thing explain accord system number theori number divin wisdom thing thing form pattern number absolut principl exist thought number one scienc number therefor found begin middl end philosophi geometri

## Split the data into training and test sets


In [87]:
# Split into X/y
from sklearn.model_selection import train_test_split, cross_val_score

x = df["documents"]
y = df["label"]
print(x.shape)
print(y.shape)
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=0)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1200,)
(1200,)
(960,)
(240,)
(960,)
(240,)


## Convert text features to numeric


In [115]:
from sklearn.feature_extraction.text import TfidfVectorizer
# sublinear_df=True, use a logarithmic form for frequency

# cv2 = TfidfVectorizer(ngram_range=(1, 2))  # 82.5%


cv2 = TfidfVectorizer(sublinear_tf=True, min_df=10, norm='l2',
                      ngram_range=(1, 2), stop_words='english')
                      

# min_df is the minimum numbers of documents a word must be present in to be kept
# norm is set to l2, to ensure all our feature vectors have a euclidian norm of 1

X_traincv = cv2.fit_transform(x_train)
x_testcv = cv2.transform(x_test)
print(X_traincv.toarray())


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Train the model

In [116]:
from sklearn.naive_bayes import MultinomialNB
mnb= MultinomialNB()

In [117]:
mnb.fit(X_traincv, y_train)

MultinomialNB()

In [118]:
mnb.score(x_testcv, y_test)*100

92.5

In [96]:
print(f"Test Text:")
print(x_test.iloc[1])

Test Text:
he has given it the attention which the subject demands as a part of the history of the country. It would be a difficult matter to get at the first American sailor, or to even guess when he existed, but that our continent was once well populated, and that its prehistoric inhabitants sailed the lakes and seas as well as trod the land, is a matter of certainty. Later, when America became known to Europeans, the new comers found Indians well provided with excellent canoes, built of bark or fashioned from logs, but they were "near shore" sailors. The author quotes one instance where a deep sea voyage was undertaken by them in the early days of the English settlers. Certain Carolina Indians, he says, wearied of the white man's sinful ways in trade, thought themselves able to deal direct with the consumers across the "Big Sea Water." So they built several large canoes and loading these with furs and tobacco paddled straight out to sea bound for England. But their ignorance of navi

In [98]:
actual_label = y_test.iloc[1]
actual_label

3

In [99]:
labelencoder.inverse_transform([actual_label])

array(['Robert C. (Chamblet) Adams'], dtype=object)

In [102]:
y_pred = mnb.predict(cv2.transform([x_test.iloc[1]]))
print(f"Predicted Y : {y_pred[0]}, author: {labelencoder.inverse_transform([y_pred[0]])}")

Predicted Y : 3, author: ['Robert C. (Chamblet) Adams']


In [ ]:
# For pd.factorize()
# print(f"Actual Y: {y_test.iloc[0]}, author: {label[y_test.iloc[0]]}")
# y_pred = mnb.predict(cv2.transform([x_test.iloc[0]]))
# print(f"Predicted Y : {y_pred[0]}, author: {label[y_pred[0]]}")
